services:
  backend:
    build:
      context: ./api # Context is the 'api' directory
      dockerfile: dockerfile
    container_name: stealthify_backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/stealthify
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: stealthify_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build:
      context: .
      dockerfile: stealthify/dockerfile
    container_name: stealthify_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: stealthify_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount the main nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf # Server-specific config file
    depends_on:
      - backend
      - frontend

volumes:
  mongo-data:
