# Stage 1: Build the Angular app
FROM node:18 AS build

# Set working directory
WORKDIR /app

# Install dependencies
COPY stealthify/package.json stealthify/package-lock.json ./
RUN npm install

# Copy the rest of the frontend app
COPY stealthify/ ./

# Build the Angular app
RUN npm run build --configuration=production

# Stage 2: Set up Nginx to serve the Angular app
FROM nginx:alpine

# Copy the built Angular app from the previous stage
COPY --from=build /app/dist/stealthify /usr/share/nginx/html

# Copy Nginx configuration from the root project directory
COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to be accessible on the server
EXPOSE 80
